add dockerfile
kubev2v/forklift pull request #1042
Opened 2024-09-18 08:26 UTC by ShakedAviv50313

2024-09-18 12:34 UTC, fabiand requested changes
Please use the name `Containerfile`

2024-09-19 07:47 UTC, yaacov commented on build/forklift-api/Containerfile
> +        io.k8s.description="Forklift - API" \
```suggestion
        io.k8s.description="Forklift API server is running Kubernetes validation and mutation webhooks for Forklift resources." \
```

2024-09-19 08:43 UTC, yaacov approved these changes
LGTM

2024-09-19 13:06 UTC, yaacov commented
@ShakedAviv50313 hi, your commit incorrectly signed off, it should have a "<" and ">" around the email, can you re-sign your commit correctly ?

2024-09-19 14:41 UTC, ernesgonzalez33 commented on build/forklift-api/Containerfile
> +        maintainer="Migration Toolkit for Virtualization Team <migtoolkit-virt@redhat.com>"
@ShakedAviv50313 please change for `"Forklift by Konveyor Community <forklift-dev@googlegroups.com>"`

2024-09-19 14:45 UTC, mnecas approved these changes
lgtm

2024-09-19 15:02 UTC, merged