MTV-1536 | Use CDI for disk transfer in cold migration feature toggle
kubev2v/forklift pull request #1171
Opened 2024-11-05 07:40 UTC by mnecas

Issue:
This is alternative to https://github.com/kubev2v/forklift/pull/1109 which removes the virt-v2v disk transfer and replaces it with te CDI. The main dissadvatage of that solution is that in case customer will have problems with the new CDI method there won't be any easy way how to go back, to the virt-v2v.

Fix:
This change adds a new feature toggle `feature_vsphere_cold_cdi` in the forklift controller. By default the feature will be enabled and in case there will be problems such as disk corruption the user can disable it.

2024-11-05 18:18 UTC, mansam requested changes
I think that parsing the environment variable should probably be done in the `settings/features.go` package, as is done for the other feature flags.

2024-11-05 19:02 UTC, mnecas commented
> I think that parsing the environment variable should probably be done in the `settings/features.go` package, as is done for the other feature flags.

100% thanks!

2024-11-06 09:14 UTC, mnecas commented on pkg/apis/forklift/v1beta1/plan.go
> +		return !p.Spec.Warm && destination.IsHost() && !useCdiForColdMigration, nil
Thanks good point, posted latest patch ptal

2024-11-06 11:26 UTC, yaacov approved these changes

2025-03-06 15:32 UTC, closed without merging